# _targets.R - generated by acme.toolkit::generate_pipeline()
# Generated: {{{timestamp}}}
# config-hash: {{{config_hash}}}
#
# This file is rendered from a Whisker template. Do not edit the analyses by
# hand; change the config and re-run generate_pipeline().

library(targets)
library(tarchetypes)

tar_option_set(
  packages = c("acme.toolkit"),
  format = "rds"
)

list(
  tar_target(
    input_file,
    "{{{data_file}}}",
    format = "file"
  ),
  tar_target(
    dataset,
    acme.toolkit::Dataset(
      data = utils::read.csv(input_file),
      name = "{{{data_name}}}"
    )
  ){{#analyses}},
  tar_target(
    {{name}},
    acme.toolkit::analyse(dataset, method = "{{method}}")
  ){{/analyses}}
)
